--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3
-- Dumped by pg_dump version 13.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: candidates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.candidates (
    id integer NOT NULL,
    first_name character varying(35) NOT NULL,
    last_name character varying(35) NOT NULL,
    national_identity character(11) NOT NULL
);


ALTER TABLE public.candidates OWNER TO postgres;

--
-- Name: employee_confirm_employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_confirm_employers (
    id integer NOT NULL,
    employer_id integer NOT NULL
);


ALTER TABLE public.employee_confirm_employers OWNER TO postgres;

--
-- Name: employee_confirms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_confirms (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    confirm_date date
);


ALTER TABLE public.employee_confirms OWNER TO postgres;

--
-- Name: employee_confirms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_confirms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_confirms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    id integer NOT NULL,
    first_name character varying(35) NOT NULL,
    last_name character varying(35) NOT NULL
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- Name: employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers (
    id integer NOT NULL,
    company_name character varying(255) NOT NULL,
    web_address character varying(50) NOT NULL,
    phone_number character varying(12) NOT NULL
);


ALTER TABLE public.employers OWNER TO postgres;

--
-- Name: job_titles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_titles (
    id integer NOT NULL,
    title character varying(100)
);


ALTER TABLE public.job_titles OWNER TO postgres;

--
-- Name: job_titles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_titles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_titles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(320) NOT NULL,
    password character varying(25) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_code_candidates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification_code_candidates (
    id integer NOT NULL,
    candidate_id integer NOT NULL
);


ALTER TABLE public.verification_code_candidates OWNER TO postgres;

--
-- Name: verification_code_employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification_code_employers (
    id integer NOT NULL,
    employer_id integer NOT NULL
);


ALTER TABLE public.verification_code_employers OWNER TO postgres;

--
-- Name: verification_codes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification_codes (
    id integer NOT NULL,
    code character varying(38) NOT NULL,
    is_verified boolean NOT NULL,
    verified_date date
);


ALTER TABLE public.verification_codes OWNER TO postgres;

--
-- Name: verification_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.verification_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: candidates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.candidates (id, first_name, last_name, national_identity) FROM stdin;
\.


--
-- Data for Name: employee_confirm_employers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee_confirm_employers (id, employer_id) FROM stdin;
\.


--
-- Data for Name: employee_confirms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee_confirms (id, employee_id, is_confirmed, confirm_date) FROM stdin;
\.


--
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees (id, first_name, last_name) FROM stdin;
\.


--
-- Data for Name: employers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employers (id, company_name, web_address, phone_number) FROM stdin;
\.


--
-- Data for Name: job_titles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_titles (id, title) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password) FROM stdin;
\.


--
-- Data for Name: verification_code_candidates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.verification_code_candidates (id, candidate_id) FROM stdin;
\.


--
-- Data for Name: verification_code_employers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.verification_code_employers (id, employer_id) FROM stdin;
\.


--
-- Data for Name: verification_codes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.verification_codes (id, code, is_verified, verified_date) FROM stdin;
\.


--
-- Name: employee_confirms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_confirms_id_seq', 1, false);


--
-- Name: job_titles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_titles_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: verification_codes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.verification_codes_id_seq', 1, false);


--
-- Name: candidates pk_candidates; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT pk_candidates PRIMARY KEY (id);


--
-- Name: employee_confirms pk_employee_confirms; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_confirms
    ADD CONSTRAINT pk_employee_confirms PRIMARY KEY (id);


--
-- Name: employees pk_employees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT pk_employees PRIMARY KEY (id);


--
-- Name: employers pk_employers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT pk_employers PRIMARY KEY (id);


--
-- Name: job_titles pk_job_titles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_titles
    ADD CONSTRAINT pk_job_titles PRIMARY KEY (id);


--
-- Name: users pk_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT pk_users PRIMARY KEY (id);


--
-- Name: verification_code_candidates pk_verification_code_candidates; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_candidates
    ADD CONSTRAINT pk_verification_code_candidates PRIMARY KEY (id);


--
-- Name: verification_code_employers pk_verification_code_employers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_employers
    ADD CONSTRAINT pk_verification_code_employers PRIMARY KEY (id);


--
-- Name: verification_codes pk_verification_codes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT pk_verification_codes PRIMARY KEY (id);


--
-- Name: candidates uc_candidates_identity_number; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT uc_candidates_identity_number UNIQUE (national_identity);


--
-- Name: job_titles uc_job_titles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_titles
    ADD CONSTRAINT uc_job_titles UNIQUE (title);


--
-- Name: users uc_users_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);


--
-- Name: verification_codes uc_verification_codes_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT uc_verification_codes_code UNIQUE (code);


--
-- Name: candidates fk_candidates_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT fk_candidates_users FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: employee_confirm_employers fk_employee_confirm_employers_employee_confirms; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_confirm_employers
    ADD CONSTRAINT fk_employee_confirm_employers_employee_confirms FOREIGN KEY (id) REFERENCES public.employee_confirms(id);


--
-- Name: employee_confirm_employers fk_employee_confirm_employers_employers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_confirm_employers
    ADD CONSTRAINT fk_employee_confirm_employers_employers FOREIGN KEY (employer_id) REFERENCES public.employers(id);


--
-- Name: employee_confirms fk_employee_confirms_employees; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_confirms
    ADD CONSTRAINT fk_employee_confirms_employees FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: employees fk_employees_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employees_users FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: employers fk_employers_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT fk_employers_users FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: verification_code_candidates fk_verification_code_candidates; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_candidates
    ADD CONSTRAINT fk_verification_code_candidates FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: verification_code_candidates fk_verification_code_candidates_verification_codes; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_candidates
    ADD CONSTRAINT fk_verification_code_candidates_verification_codes FOREIGN KEY (id) REFERENCES public.verification_codes(id);


--
-- Name: verification_code_employers fk_verification_code_employers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_employers
    ADD CONSTRAINT fk_verification_code_employers FOREIGN KEY (employer_id) REFERENCES public.employers(id);


--
-- Name: verification_code_employers fk_verification_code_employers_verification_codes; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_employers
    ADD CONSTRAINT fk_verification_code_employers_verification_codes FOREIGN KEY (id) REFERENCES public.verification_codes(id);


--
-- PostgreSQL database dump complete
--

